# Тема 10. Декораторы и исключения
Отчет по Теме #10 выполнил:
- Удовиченко Сергей Олегович
- ИНО ЗБ ПОАС 22-2

| Задание | Сам_раб |
| ------ | ------ |
| Задание 1 | + |
| Задание 2 | + |
| Задание 3 | + |
| Задание 4 | + |
| Задание 5 | + |

Работу проверили:
- к.э.н., доцент Панов М.А.
## Самостоятельная работы №10

### 1) Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор.

```python
import time

def time_(func):
  def wawa(*arg, **kwarg):
    start_time = time.perf_counter()
    result = func(*arg, **kwarg)
    end_time = time.perf_counter()
    time_end = start_time - end_time
    print(f"\nФункция: {func.__name__} выполнялась за {time_end:.2f} секунд.")
    return result
  return wawa

@time_
def fibonacci():
  fib1 = fib2 = 1

  for i in range(2, 200):
    fib1, fib2 = fib2, fib1 + fib2
    print(fib2, end=' ')

if __name__ == '__main__':
  fibonacci()
```
### Результат:
  ![Меню](https://github.com/SergUdav/PI/blob/LR10/pic/1.png)

### 2) Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой. проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла

```python
def read_file(file_name):
  try:
    with open(file_name) as file:
      text = file.read()
      if not text:
        raise ValueError("Файл пустой")
      print(text)
  except FileNotFoundError:
    print("Файл не найден")
  except ValueError as e:
    print(e)

read_file("text_1.txt")
read_file("text_2.txt")
read_file("text_3.txt")
```
### Результат:
  ![Меню](https://github.com/SergUdav/PI/blob/LR10/pic/2.png)

### 3) Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которы в которых исключение вызывается и нет.

```python
def two():
  try:
    user = input()
    user = int(user)
    res = user + 2
    print(res)
  except TypeError:
    print("adsasda")
  except ValueError:
    print("Неподходящий тип данных. Ожидалось число.")

two()
```
### Результат:
  ![Меню](https://github.com/SergUdav/PI/blob/LR10/pic/3.png)

### 4) Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями

```python
def dec(func):
    def wr(*args, **kwargs):
        print("Декоратор: Функция начинает выполнение.")
        result = func(*args, **kwargs)
        print("Декоратор: Функция завершила выполнение.")
        return result
    return wr

@dec
def gr(name):
    print(f"Привет, {name}!")

@dec
def cal_sum(a, b):
    print(f"Сумма: {a + b}")

gr("FKfkkf")
cal_sum(5, 3)
```
### Результат:
  ![Меню](https://github.com/SergUdav/PI/blob/LR10/pic/4.png)

### 5) Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение

```python
class InvalidInputError(Exception):
  pass


def get_positive_number():
    try:
        number = int(input())
        if number <= 0:
            raise InvalidInputError("Введено неположительное число.")
        return number
    except ValueError:
        raise InvalidInputError("Введено не число.")

def calculate_square(number):
  result = number ** 2
  return result

print(calculate_square(get_positive_number()))
```
### Результат:
  ![Меню](https://github.com/SergUdav/PI/blob/LR10/pic/5.png)
